version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: studybuddy-postgres
    restart: always
    environment:
      POSTGRES_DB: studybuddy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # בעתיד תוכל להוסיף גם את אפליקציית ה-Spring Boot כאן:
  # backend:
  #   build: .
  #   container_name: studybuddy-backend
  #   ports:
  #     - "8888:8080"
  #   depends_on:
  #     - postgres
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studybuddy_db
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: changeme123

volumes:
  pgdata:
